Insert Into ELIGIBLITY_DTLS (ELIGIBLITY_ID,PLAN_NAME, PLAN_STATUS,CASE_NUM,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,DENIAL_REASN,START_DATE,END_DATE) 
Values(101,'SNAP','APPROVED',201,'Vinod Jupalli',14407,50000,null,'2022-05-12','2023-05-12');
Insert Into ELIGIBLITY_DTLS (ELIGIBLITY_ID,PLAN_NAME, PLAN_STATUS,CASE_NUM,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,DENIAL_REASN,START_DATE,END_DATE) 
Values(102,'SNAP','APPROVED',202,'Pavan Jupalli',14457,60000,null,'2022-05-12','2023-05-12');	


Insert Into ELIGIBLITY_DTLS (ELIGIBLITY_ID,PLAN_NAME, PLAN_STATUS,CASE_NUM,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,DENIAL_REASN,START_DATE,END_DATE) 
Values(103,'SNAP','DENIED',203,'Charan Jupalli',14409,null,'NOT ELIGIBLE',null,null);
Insert Into ELIGIBLITY_DTLS (ELIGIBLITY_ID,PLAN_NAME, PLAN_STATUS,CASE_NUM,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,DENIAL_REASN,START_DATE,END_DATE) 
Values(104,'SNAP','DENIED',204,'Vishuruth Jupalli',14408,null,'PAN NUMBER IS MISSING',null,null);


Insert Into ELIGIBLITY_DTLS (ELIGIBLITY_ID,PLAN_NAME, PLAN_STATUS,CASE_NUM,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,DENIAL_REASN,START_DATE,END_DATE) 
Values(105,'CCAP','APPROVED',205,'Karti',14407,70000,null,'2022-05-12','2023-05-12');
Insert Into ELIGIBLITY_DTLS (ELIGIBLITY_ID,PLAN_NAME, PLAN_STATUS,CASE_NUM,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,DENIAL_REASN,START_DATE,END_DATE) 
Values(106,'CCAP','APPROVED',206,'Vishal',14457,30000,null,'2022-05-12','2023-05-12');	


Insert Into ELIGIBLITY_DTLS (ELIGIBLITY_ID,PLAN_NAME, PLAN_STATUS,CASE_NUM,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,DENIAL_REASN,START_DATE,END_DATE) 
Values(107,'CCAP','DENIED',207,'Surya',13409,null,'Verification Required',null,null);
Insert Into ELIGIBLITY_DTLS (ELIGIBLITY_ID,PLAN_NAME, PLAN_STATUS,CASE_NUM,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,DENIAL_REASN,START_DATE,END_DATE) 
Values(108,'CCAP','DENIED',208,'Mahesh',13408,null,'ADHAR NUMBER IS MISSING',null,null);	

Insert Into ELIGIBLITY_DTLS (ELIGIBLITY_ID,PLAN_NAME, PLAN_STATUS,CASE_NUM,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,DENIAL_REASN,START_DATE,END_DATE) 
Values(109,'Medicaid','APPROVED',209,'Vaishnav',12407,90000,null,'2022-05-12','2023-05-12');
Insert Into ELIGIBLITY_DTLS (ELIGIBLITY_ID,PLAN_NAME, PLAN_STATUS,CASE_NUM,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,DENIAL_REASN,START_DATE,END_DATE) 
Values(110,'Medicaid','APPROVED',210,'Kalyan',12457,20000,null,'2022-05-12','2023-05-12');	


Insert Into ELIGIBLITY_DTLS (ELIGIBLITY_ID,PLAN_NAME, PLAN_STATUS,CASE_NUM,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,DENIAL_REASN,START_DATE,END_DATE) 
Values(111,'Medicaid','DENIED',211,'Arjun',12409,null,'NOT AVLAIBLE',null,null);
Insert Into ELIGIBLITY_DTLS (ELIGIBLITY_ID,PLAN_NAME, PLAN_STATUS,CASE_NUM,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,DENIAL_REASN,START_DATE,END_DATE) 
Values(112,'Medicaid','DENIED',212,'Sai Tej',12408,null,'PIN NUMBER IS MISSING',null,null);	

Insert Into ELIGIBLITY_DTLS (ELIGIBLITY_ID,PLAN_NAME, PLAN_STATUS,CASE_NUM,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,DENIAL_REASN,START_DATE,END_DATE) 
Values(113,'Medicare','APPROVED',213,'Varun Tej',16407,55000,null,'2022-05-12','2023-05-12');
Insert Into ELIGIBLITY_DTLS (ELIGIBLITY_ID,PLAN_NAME, PLAN_STATUS,CASE_NUM,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,DENIAL_REASN,START_DATE,END_DATE) 
Values(114,'Medicare','APPROVED',214,'Ravi Teja',16457,66000,null,'2022-05-12','2023-05-12');	


Insert Into ELIGIBLITY_DTLS (ELIGIBLITY_ID,PLAN_NAME, PLAN_STATUS,CASE_NUM,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,DENIAL_REASN,START_DATE,END_DATE) 
Values(115,'Medicare','DENIED',215,'Ram Charan',17409,null,'CARD IS NOT VALID',null,null);
Insert Into ELIGIBLITY_DTLS (ELIGIBLITY_ID,PLAN_NAME, PLAN_STATUS,CASE_NUM,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,DENIAL_REASN,START_DATE,END_DATE) 
Values(116,'Medicare','DENIED',216,'NTR',17408,null,'PHONE NUMBER IS MISSING',null,null);	

Insert Into ELIGIBLITY_DTLS (ELIGIBLITY_ID,PLAN_NAME, PLAN_STATUS,CASE_NUM,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,DENIAL_REASN,START_DATE,END_DATE) 
Values(117,'QHP','APPROVED',217,'Venky',11407,50300,null,'2022-05-12','2023-05-12');
Insert Into ELIGIBLITY_DTLS (ELIGIBLITY_ID,PLAN_NAME, PLAN_STATUS,CASE_NUM,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,DENIAL_REASN,START_DATE,END_DATE) 
Values(118,'QHP','APPROVED',218,'Nag',11457,62000,null,'2022-05-12','2023-05-12');	


Insert Into ELIGIBLITY_DTLS (ELIGIBLITY_ID,PLAN_NAME, PLAN_STATUS,CASE_NUM,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,DENIAL_REASN,START_DATE,END_DATE) 
Values(119,'QHP','DENIED',219,'Bala Krishna',18409,null,'SSN NUMBER IS INVALID',null,null);
Insert Into ELIGIBLITY_DTLS (ELIGIBLITY_ID,PLAN_NAME, PLAN_STATUS,CASE_NUM,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,DENIAL_REASN,START_DATE,END_DATE) 
Values(120,'QHP','DENIED',220,'Chiru',18408,null,'Account NUMBER IS MISSING',null,null);

